### ISSUE TITLE
[FEATURE][COMMON] 프로젝트 기본 설정

### ISSUE THREAD

**Issue by jiwon11** [The-Dark-Nights/back-end#1]
## Description
새로운 기능 추가에 관련 된 이슈 템플릿입니다.

---

## TODO
- [x]  build.gradle 설정
- [x] application.yml 설정
- [x] application-oauth.yml 설정
---

## ETC

---
* 없음
